---
- name: install gnome-shell-pomodoro
  ansible.builtin.apt:
    name: gnome-shell-pomodoro
    update_cache: true
  become: true

- name: create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/gnome-pomodoro"
    state: directory
    mode: '0755'

# sync addons
- name: link gnome-pomodoro directory
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/Insync/michael.w.baroody@gmail.com/Google\ Drive/$HOME/.local/share/gnome-pomodoro"
    dest: "{{ ansible_env.HOME }}/.local/share/gnome-pomodoro"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    state: link
